# Generated by Django 6.0.5 on 2026-07-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogimage',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
