# Generated by Django 6.0.5 on 2026-06-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subfolder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
